---
title: "Получение сведений о системе"
author: "Смирнов Михаил"
engine: knitr
format: 
    md:
        output-file: README.md
---

# Системы аутентификации и защиты от несанкционированного доступа

## Лабораторная работа №1

## Цель работы

Получить сведения об используемой системе

## Исходные данные

1.  ОС Windows 10
2.  WSL2 
3.  Ноутбук ASUS

## План

1.  Выполнить команду uname -r
2.  Выполнить команду cat /proc/cpuinfo \| grep "model name"
3.  Выполнить команду journalctl -q -b \| tail -n 30

## Ход работы

1\.  Первым шагом выполним команду uname -r для вывода информации о системе.

```{bash}
uname -r
```

2\. Далее выполним команду cat /proc/cpuinfo | grep "model name" для вывода информации о процессоре, строки которой содержат "model name".

```{bash}
cat /proc/cpuinfo | grep "model name"
```

3\. Позже выполним команду dmesg | tail -n 30 для вывода последних 30 строк логов.

```{bash}
dmesg | tail -n 30
```

## Оценка результата

В результате лабораторной работы №1 мы получили основную информацию об ОС и процессоре и логи системы.

## Вывод

Таким образом, мы научились работать с базовыми командами Linux и получать информацию об операционной системе.