---
title: "Применение средств и методов OSINT"
author: "Смирнов Михаил БИСО-03-20"
format: 
    md:
        output-file: README.md
engine: knitr
---
Open source intelligence (OSINT) – разведывательная дисциплина, включающая в себя поиск, выбор
и сбор разведывательной информации из общедоступных источников, а также её анализ.

Такими источниками информации могут быть:

- поисковые машины – Google, Bing, Yandex...

- специализированные поисковые системы – intelx.io, Shodan, Censys...

- порталы открытых данных – Github Awesome Lists, https://opendata.digital.gov.ru/

- материалы профильных конференций

- социальные сети, профильные блоги и т.д.

- официальные сайты компаний
## Цель работы
1. Освоить базовые подходы процессов OSINT
2. Освоить современные инструменты поиска и сбора информации
3. Освоить инструменты совместной работы в ходе аналитической деятельности


## Задание
1. Собрать информацию о компании Инфосистемы Джет и их продуктах.
2. Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.
3. Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.
4. Сформировать представление о рынке отечественных решений ИБ.

## Ход работы
### 1. Полное название компании

Полное название компании - АКЦИОНЕРНОЕ ОБЩЕСТВО "ИНФОСИСТЕМЫ ДЖЕТ"

### 2. Структура компании (при наличии публичной информации)

